Document: busybox
Title: Debian busybox Manual
Author: <insert document author here>
Abstract: This manual describes what busybox is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/busybox/busybox.sgml.gz

Format: postscript
Files: /usr/share/doc/busybox/busybox.ps.gz

Format: text
Files: /usr/share/doc/busybox/busybox.text.gz

Format: HTML
Index: /usr/share/doc/busybox/html/index.html
Files: /usr/share/doc/busybox/html/*.html
